### ISSUE TITLE
missing mp3 files for sound effects and music

### ISSUE THREAD

**Issue by obiot** [abdellatifAhammad/bounce_tales#1]
Hi Nice game !

When loading under Safari (that does not support .ogg), loading fails because of missing mp3 files.

melonJS will try to load audio files based on both supported format and provided assets type as specified through the `audio.init()` method:
https://github.com/abdellatifAhammad/bounce_tales/blob/38c7309064b869f42ebedf2b30d118a079886cd8/src/index.js#L28

**Comment by abdellatifAhammad** [comment]
Hi mr Olivier, thanks a lot for pointing to this issue,I did't test on Safari since I don't have it, but I am 100% percent sure that I need to put the mp3 files also there, thanks a lot sir.

**Comment by obiot** [comment]
you are welcome! And yes, just put the mp3 version in the same location :)

Looking forward to play more of your game as your project progresses !

**Comment by abdellatifAhammad** [comment]
thanks a lot Olivier for indicating this issue, I added the mp3 files, so that will fix the issue for now.
